### ISSUE TITLE
Create Ricardian Contracts

### ISSUE THREAD

**Issue by lukestokes** [eosdac/daccustodian#1]

**Comment by lukestokes** [comment]
Example: https://github.com/eosdac/eosdactoken/blob/master/tokenmember_rc.md

**Comment by kasperfish** [comment]
![image](https://user-images.githubusercontent.com/5130772/44303084-e37dc780-a337-11e8-8b08-d5f3bec4d0b2.png)
think this is not really descriptive

**Comment by dallasjohnson** [comment]
done
