### ISSUE TITLE
Add `claimpay` action to be used instead of of the `paypending`

### ISSUE THREAD

**Issue by dallasjohnson** [eosdac/daccustodian#12]
For now this would just take pending pay actions from the pendingpay table based on the `claimer` but could be extended to included time delays on transactions and/or approval checks.

**Comment by lukestokes** [comment]
@dallasjohnson questions about the payment came up in the meeting today after you left. I see `TOKEN_CONTRACT` is used, but that seems to be a token contract account:

https://github.com/eosdac/daccustodian/blob/542e2cef149090d7416c39e334dc00fbaac38fb9/daccustodian.hpp#L6

Does the current design take into account the `eosdacthedac` funds account? It's not the token contract, but it's a multisig account which holds the DAC funds. Do we have to make some changes to support that or is that not a problem? DAC payments should come out of the DAC funds account which is currently configured as a multisig, though I imagine the code level permissions could be done differently?

@michaeljyeates may have some thoughts as well.

**Comment by dallasjohnson** [comment]
The current design uses the TOKEN_CONTRACT variable (either set as eosdactoken by default or injected via the eosio-cpp compile command) for tracking the balance changes between all the accounts so that the votes weight can be tracked. The currently contract assumes staking would be received/returned by this contract and also assumes that payments to custodians would also be from this contract. To change this to come from a different account would need code changes but I think it would quite simply a case of changing `_self` to `N(eosdacthedac)` but then the permissions would also need to be changed on `eosdacthedac` to allow this contract to act with the same permission level as the multisig permission on that account to be allowed to transfer funds.

**Comment by lukestokes** [comment]
@michaeljyeates thoughts?

**Comment by michaeljyeates** [comment]
Yes, agreed with Dallas, we will add a permission to eosdacthedac which will allow daccustodian@eosio.code to transfer but it will require a delayed transaction, so the payment will actually be sent straight away but it will be a delayed transaction which we can cancel

**Comment by dallasjohnson** [comment]
This is code complete from the elections contract now including having the contract as a config option in case it's needed by any other DAC 😉 This just needs testing with the delayed transaction etc. Will leave the issue open for now.

**Comment by dallasjohnson** [comment]
Have tested `claimpay` with a deferred transaction and it is working, although now being a deferred transaction it is difficult to automate testing for.
