### ISSUE TITLE
Update Ricardian Contracts to follow our consistent pattern

### ISSUE THREAD

**Issue by lukestokes** [eosdac/daccustodian#17]
![image](https://user-images.githubusercontent.com/344748/45784043-1f54c700-bc2d-11e8-9f96-3e8dd4e95550.png)

The code does some `replaceVars` stuff in the UI which seems to look for specific patterns.

**Comment by lukestokes** [comment]
The format and the content should be reviewed.

**Comment by dallasjohnson** [comment]
This needs further discussion about what is expected. Then I can fill in the details based on my impression of the behaviour. Then Rob or Saro can sanity check.

**Comment by lukestokes** [comment]
Let's use this: https://github.com/EOSIO/eos/tree/master/scripts/abi_to_rc

**Comment by dallasjohnson** [comment]
done
