### ISSUE TITLE
Start the DAC with only Active permissions being modified each election period.

### ISSUE THREAD

**Issue by lukestokes** [eosdac/daccustodian#18]
Leave the owner permissions as is for now (i.e. Michael, Rob, Luke) until the elected Custodians are completely confident with the functioning of the DAC, then they can create a worker proposal to modify the code to include owner permission changing also. This bit of centralization in the beginning makes sense to protect the DAC and was discussed in the all-hands meeting and dev meeting on Sep 24th.

**Comment by dallasjohnson** [comment]
This is not an issue since the owner permission is already retained elsewhere. My mistake 🤦‍♂️
