### ISSUE TITLE
Use a more verbose ABI format when creating our structs

### ISSUE THREAD

**Issue by lukestokes** [eosdac/daccustodian#20]
This avoids some current limitations with the compiler and Scatter integrations.

**Comment by dallasjohnson** [comment]
Done manually. I tried to use the ABI gen since it was apparently improved but it didn't work well enough for our needs. This will need testing by @kasperfish or @nanonano7 since they experienced the initial problem and then close the issue if happy.

**Comment by dallasjohnson** [comment]
done.
