### ISSUE TITLE
To allow for some time for people to register as candidates, return false (temporarily) on custodian votes

### ISSUE THREAD

**Issue by lukestokes** [eosdac/daccustodian#21]
Once we're ready to open up custodian voting (we talked on our call about allow for two weeks for custodians to register), we can deploy and updated contract that removes the return false.

We discussed in the future possibly having value with a boolean for disabling voting, but since this isn't yet defined in the constitution, we'll leave things as is for now.

**Comment by lukestokes** [comment]
As discussed in today's meeting, let's have it return an error message we can display to the front end.

**Comment by dallasjohnson** [comment]
This is done and can be controlled via a compile time macro.
The latest build was built with:
    
    eosio-cpp -DTOKEN_CONTRACT='"eosdactokens"' -DVOTING_DISABLED=1 -o daccustodian_voting_disabled.wast daccustodian.cpp

To re-enable voting build again leaving out the `-DVOTING_DISABLED=1` part.
