### ISSUE TITLE
Hash of bio in candidates struct

### ISSUE THREAD

**Issue by jchung00** [eosdac/daccustodian#30]
It says in the Readme that the hash of the bio is on the candidates table but it is not there. It doesn't seem like it's actually part of the struct and the updatebio action doesn't actually emplace anything onto the table.

**Comment by dallasjohnson** [comment]
Sorry, the README is out of date. We used to save the bio hash in an earlier iteration but now just pass it through the contract for auth purposes and the actual data is saved off chain. There is not logic in contract code that needs to access the bio so there is no need to persist it. I'll remove it from the README.
