### ISSUE TITLE
assert with error message when calling votecust with empty array

### ISSUE THREAD

**Issue by ghost** [eosdac/daccustodian#8]

**Comment by dallasjohnson** [comment]
I don't agree with this one. There is nothing to say you must vote for a certain number of custodians and currently there is no way to remove votes. This could be used to remove as active vote by passing an empty array. Alternatively I could modify the action to remove the vote if the array is empty.

**Comment by ghost** [comment]
very true, I didn't think about that. I'll need to modify the GUI to support sending an empty array so that voters are able to withdraw their votes.
